version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sh03m2a5h"
    commit-message:
      prefix: "deps(go)"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "sh03m2a5h"
    commit-message:
      prefix: "ci"
      include: "scope"